[package]
name = "polars_bson"
version = "0.1.0"
edition = "2024"

[dependencies]
polars-time = "0.46.0"
polars-core = "0.46.0"
bson = "2.14.0"
mongodb = { version = "3.2.3", features = ["sync"] }
atoi_simd = "0.16.0"
simdutf8 = "0.1.5"
fast-float2 = "0.2.3"

[dependencies.polars]
version = "0.46.0"
features = ["lazy", "dtype-full"]
